import Head from "next/head";
import { Archivo } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import LoadingComponent from "@/components/LoadingComponent";
import Profile from "@/components/Profile";

const archivo = Archivo({ subsets: ["latin"] });

export default function Home() {
  const [loadingScreen, setLoadingScreen] = useState(true);
  useEffect(() => {
    setInterval(() => setLoadingScreen(false), 1000);
  }, []);

  return (
    <div className={`${styles.main__container} ${archivo.className}`}>
      <Head>
        <title>Rodrigo - Portfolio 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loadingScreen ? (
        <LoadingComponent></LoadingComponent>
      ) : (
        <Profile></Profile>
      )}
    </div>
  );
}
