import Head from "next/head";
import { Archivo } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { useEffect, useState } from "react";
import LoadingComponent from "@/components/LoadingComponent";
import Profile from "@/components/Profile";
import { timer } from "@/utils/utils";

const archivo = Archivo({ subsets: ["latin"] });

export default function Home() {
  const [loadingScreen, setLoadingScreen] = useState(false);
  // useEffect(() => {
  //   setInterval(() => setLoadingScreen(false), timer);
  // }, []);

  return (
    <div className={`${styles.main__container} ${archivo.className}`}>
      <Head>
        <title>Rodrigo - Portfolio 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rocket-solid.svg" />
      </Head>
      {loadingScreen ? <></> : <Profile></Profile>}
    </div>
  );
}
