import Head from "next/head";
import Image from "next/image";
import { Archivo } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ImageComponent from "@/components/Image";

const archivo = Archivo({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rodrigo - Portfolio 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${archivo.className}`}>
        <ImageComponent></ImageComponent>
        <h1 className={`${styles.title}`}>
          Rodrigo<br></br>_Carvalho
        </h1>
        <p className={`${styles.description}`}>
          Apaixonado por tecnologia, com experiência em desenvolvimento e
          escalabilidade de sistemas e plataformas, colaborando com o
          crescimento e inovação em importantes empresas, como Farmácias APP,
          Riachuelo e Magalu.
        </p>
      </main>
    </>
  );
}
